### ISSUE TITLE
make install fails on static build.

### ISSUE THREAD

**Issue by dp289m** [dyne/frei0r#110]
Frei0r fails to install static build.

https://pastebin.com/raw/ivEdfGuK

**Comment by realies** [comment]
Same issue here. #18 suggest static builds are not possible.

**Comment by ddennedy** [comment]
impossible. “Plugins” implies dynamically loaded.

**Comment by realies** [comment]
@ddennedy, thanks, how can we get around the `cannot stat` errors and rely on dynamic plugins?

**Comment by jaromil** [comment]
use dlopen() on .so files shipped along your program, don't --enable-static, it does not work.
