### ISSUE TITLE
missing release in github of version 1.6.1

### ISSUE THREAD

**Issue by martinr92** [dyne/frei0r#12]
In the last commit you increased the version number to 1.6.1 but it's sill missing in the Github releases:
https://github.com/dyne/frei0r/releases
Can you please also add the release there?

**Comment by ddennedy** [comment]
The version may increment any time prior to a release. Bumping the version in source implies nothing about the release date. Use master HEAD if you want a v1.6.1 pre-release.

**Comment by martinr92** [comment]
Thanks for the release 👍
