### ISSUE TITLE
Web page outdated malware risky

### ISSUE THREAD

**Issue by Anyeos** [dyne/frei0r#122]
I found this project on https://www.dyne.org/software/frei0r
and the links there are broken or misspelled.
For example, instead of "github" it say "githhub" that carry you to another web site (that is not the real github).
The links about "latest announcement" and "overview of code activity" are broken. That made me think that the project is dead.
And there may be more things to fix.

So I guess the site needs to be reviewed.

**Comment by jaromil** [comment]
@Anyeos thanks for noticing! I corrected the errors reported and that I could detect, anything else let me know. there is an easier to navigate homepage on https://frei0r.dyne.org while this is up mostly for historical reasons
