### ISSUE TITLE
Need help with backporting recent commits for Flathub maintainers

### ISSUE THREAD

**Issue by Efenstor** [dyne/frei0r#166]
Several latest flatpak releases of Kdenlive on Flathub suffer from crashes with the Bezier Curves effect. The bug which was fixed in the recent commits is critical. So basically there is a need for a new frei0r release. Here is the discussion in the Flathub repo: https://github.com/flathub/org.kde.kdenlive/issues/225

I can't do much myself, I am a user, not a developer.

**Comment by jaromil** [comment]
@Efenstor expect a new release early this week

**Comment by jaromil** [comment]
Here we go https://github.com/dyne/frei0r/releases/tag/v2.3.0

**Comment by Efenstor** [comment]
Great!!! Thank you very much!
