### ISSUE TITLE
clang-format the C and C++ source code

### ISSUE THREAD

**Issue by Jonadabe** [dyne/frei0r#172]
Hi everyone,

It's awesome all the work in here.

What do you think if all the source code had the **same formatting**?
Well, clang-format could be an answer.
https://clang.llvm.org/docs/ClangFormatStyleOptions.html
https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.6 (with releases for all platform)

Another suggestion would be the adopting of .editorconfig repo here:
**https://github.com/editorconfig**

Maybe not, but still I must suggest it strongly, and you decide what's best for the project.
Thank you all, again!

**Comment by jaromil** [comment]
I have two reasons against this proposal, in no particular order:
1. lose trace of coding style by different contributors, which has some historical relevance and in future may help to distinguish human-written code from machine.
2. introduce a commit that will force a change upon all code and so may create disruption for any future merging of code that references versions before this modification.
