### ISSUE TITLE
Lack of kaleidoscope filter

### ISSUE THREAD

**Issue by gbendy** [dyne/frei0r#174]
Would you be open to a PR to add my kaleid0sc0pe filter to the core codebase?

https://github.com/gbendy/kaleidoscope/

**Comment by jaromil** [comment]
@gbendy you are welcome! is there a way to build it without SSE specific instructions?

**Comment by gbendy** [comment]
Yes, there's a CMake option. Can default that to off. Or can just make it rely on the `__SSE2__` define that other filters like aech0r/colgate/medians use,

BTW, I got it building in the frei0r codebase today. Just haven't tested the output yet.

**Comment by jaromil** [comment]
@gbendy excellent, will follow up on the PR

**Comment by jaromil** [comment]
dears, any clues about this? https://github.com/rdp/ffmpeg-windows-build-helpers/issues/706 I am not an expert of latest C++ stuff nor Win64 platform, so worst case scenario I'd skip build for that platform but it's a pity

**Comment by gbendy** [comment]
Cross compiler configuration related. Can detect and deal with the problem at `cmake` time https://github.com/dyne/frei0r/pull/179

**Comment by gbendy** [comment]
All works fine if you build in native Win64. Seems so bizarre that even now some C++11 features aren't supported in some compiler setups.
