### ISSUE TITLE
get_param_value F0R_PARAM_BOOL alignment trapped

### ISSUE THREAD

**Issue by urjaman** [dyne/frei0r#191]
Looking at this line:
https://github.com/dyne/frei0r/blob/fdc9f32a4f76fe9bd9ab2e90580059f057fa5c8f/include/frei0r.hpp#L104

and comparing to set_param_value,
shouldnt the *static_cast<f0r_param_bool*>(ptr) be a *static_cast<bool*>(ptr) here?

Yours truly,
someone who hit an Alignment fault on this line trying to start kdenlive on ARM32

**Comment by rrrapha** [comment]
Yes, I think this line should be changed to this:
`	    = *static_cast<bool*>(ptr) ? 1.0 : 0.0;`
