### ISSUE TITLE
windows 10 does not load dll

### ISSUE THREAD

**Issue by audas** [dyne/frei0r#21]
IN FFMPEG when looking for frei0r effect in correct environment path results in "could not find module" and fails.

I is definitely finding the correct pathway and simply "not seeing" the .dll files ?

This works fine in windows 7

**Comment by namikiri** [comment]
I think you should look at your `FFmpeg` build first, that's probably not a `Frei0r` fault.
Windows builds of `FFmpeg` usually have `Frei0r` libraries statically linked.

Where did you get your build of `FFmpeg`? What version? Was it build with `--enable-frei0r` flag?

**Comment by ddennedy** [comment]
> Windows builds of FFmpeg usually have Frei0r libraries statically linked.

I highly doubt that. Each frei0r effect has the same function names! Someone would have to make some major fork of frei0r (and ffmpeg?) to do that. But your point about the checking the ffmpeg and frei0r builds is correct. This project is not responsible for any builds of frei0r; it only provides source code.

**Comment by audas** [comment]
Totally understand about this being a code repository only - but am really struggling here.

In the frei0r source documents and readme it talks about how the effects are loaded - 

from the documentation linked from this repository -

https://frei0r.dyne.org/codedoc/html/group__pluglocations.html

> FREI0R_PATH Environment Variable

>FREI0R_PATH=/home/foo/frei0r-plugins:/usr/lib/frei0r-1:/etc/frei0r

>On Windows platforms a semicolon ';' must be used instead of colon ':' to separate FREI0R_PATH entries (due to the way filenames are interpreted), hence a cross-platform host application should detect the platform running and adjust the parsed char accordingly, for example:

>FREI0R_PATH=C: Files-1;%PROGRAMFILES%-1

I am using the zeranoe windows builds. Nothing works on windows 10 - I have been using them consistently on previous windows builds along with Ubuntu - but they simply will not work on windows 10.

I totally understand that this is merely a code repository - however I was REALLY hoping there might be some insight into this issue and some suggestion as Ive lost many days on this.

**Comment by ddennedy** [comment]
I am OK to leave it open for a while to see if someone can chime and help. I also suggest you ask on the [zeranoe forum](https://ffmpeg.zeranoe.com/forum/).

**Comment by audas** [comment]
Thanks for taking the time to see if anything comes up. I have an open question there, zeranoe and stackoverflow.

I am so perplexed.

Its simply "not seeing" the file. So strange. I have considered blank spaces, all kinds of things.

Possibly something to do with Administrator accounts and user accounts under the new windows 10 frame work - or a backslash issue..

I can work on this on my windows machines - but not on my tens.

When I resolve it I will come and let you guys know.

**Comment by jaromil** [comment]
Is this problem occurring only with frei0r dll plugins or with any dll?

are you using dlopen()?

**Comment by audas** [comment]
Only tried with frei0r.

Never ended up resolving this - back on windows 7, there is information on the Freds Image Magic Scripts which detail implementing his scripts on windows which may be of some help.

It may well have also had something to do with installing windows linux environment stuff - this was almost 12 months ago. There is a new Windows 10 method of running linux stuff which windows 7 had to manually install.

**Comment by jaromil** [comment]
ACK. closing issue then.
