### ISSUE TITLE
sprintf src and dest the same not allowed

### ISSUE THREAD

**Issue by dcb314** [dyne/frei0r#22]
filter/measure/pr0file.c:327:5: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]

Source code is

    sprintf(str,"%s %s",str,"Mk1= -----");

man sprintf says:

       Some programs imprudently rely on code such as the following

           sprintf(buf, "%s some further text", buf);

       to append text to buf.  However, the standards explicitly note that the
       results are undefined if source and destination  buffers  overlap  when
       calling  sprintf(), snprintf(), vsprintf(), and vsnprintf().  Depending
       on the version of gcc(1) used, and the compiler options employed, calls
       such as the above will not produce the expected results.

Many more examples in the same file. Suggest compile with -Wrestrict.

**Comment by jaromil** [comment]
Well spotted. I agree with the adoption of this flag. Thanks!

**Comment by jaromil** [comment]
For now I've limited the usage of `-Wrestrict` on clang builds since most distros ship gcc compilers that are too old to support it. OSX builds use clang and one is ran at every commit, logs visible here https://travis-ci.org/dyne/frei0r

**Comment by ddennedy** [comment]
That's great re additional option on clang and that Travis can run macOS, but the macOS build is showing usage of gcc instead and complaining and unknown warning option in the build log. :-/
