### ISSUE TITLE
frei0r.dodge does not work correctly

### ISSUE THREAD

**Issue by smolnp** [dyne/frei0r#29]
In the kdenlive and flowblade plugin frei0r.dodge does not work correctly
![v-tgkvo6odc](https://user-images.githubusercontent.com/26217756/44106512-8868e5ce-9ffd-11e8-8af9-208ae11e5cd1.jpg)
Serhu in the red rectangle noted how he should work correctly

**Comment by ddennedy** [comment]
A workaround is to use `cairoblend` with blend mode = "colordodge"
