### ISSUE TITLE
Compilation problem with OpenCV

### ISSUE THREAD

**Issue by rrrapha** [dyne/frei0r#70]
On OpenBSD, the following error occurs when compiling facedetect/facebl0r:

```
$ cmake .
$ make VERBOSE=1
[  1%] Building CXX object src/filter/facebl0r/CMakeFiles/facebl0r.dir/facebl0r.cpp.o
cd /tmp/frei0r/src/filter/facebl0r && /usr/bin/c++  -Dfacebl0r_EXPORTS -I/tmp/frei0r/include -I/usr/local/include/opencv  -g -DNDEBUG -fPIC   -o CMakeFiles
/facebl0r.dir/facebl0r.cpp.o -c /tmp/frei0r/src/filter/facebl0r/facebl0r.cpp
/tmp/frei0r/src/filter/facebl0r/facebl0r.cpp:21:10: fatal error: 'opencv2/opencv.hpp' file not found
#include <opencv2/opencv.hpp>
         ^~~~~~~~~~~~~~~~~~~~
```

Workaround:
`$ cmake . -DCMAKE_CXX_FLAGS=-I/usr/local/include`

**Comment by ddennedy** [comment]
I appreciate your explanation, and I am comfortable now to give it a try. After all, we can easily revert it if it becomes a problem, right? What do you say @jaromil and @d-j-a-y?

**Comment by rrrapha** [comment]
@d-j-a-y Yes, this would work too, but it  adds the opencv include flags to all plugins, not only the ones that need them.

**Comment by rrrapha** [comment]
I came to the conclusion that FindOpenCVConfig.cmake should be removed completely.
This means that cmake relies on the OpenCVConfig.cmake file provided by OpenCV.

It is likely that this works on all systems (if OpenCV is installed correctly).
(If OpenCV is installed in a non-standard location, the path can be set via environment variable OpenCV_DIR.)

Using the config mode of find_package makes sure that all OpenCV_* variables are set correctly.
On my system:
```
-- OpenCV_CONFIG=/usr/local/share/OpenCV/OpenCVConfig.cmake
-- OpenCV_CONFIG_PATH=/usr/local/share/OpenCV
-- OpenCV_DIR=/usr/local/share/OpenCV
-- OpenCV_FOUND=1
-- OpenCV_INCLUDE_DIRS=/usr/local/include;/usr/local/include/opencv
-- OpenCV_INSTALL_PATH=/usr/local
-- OpenCV_LIBRARIES=opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;[...]
-- OpenCV_LIBS=opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;[...]
-- OpenCV_VERSION=3.4.5
-- OpenCV_VERSION_COUNT=3
-- OpenCV_VERSION_MAJOR=3
-- OpenCV_VERSION_MINOR=4
-- OpenCV_VERSION_PATCH=5
-- OpenCV_opencv_aruco_FOUND=TRUE
-- OpenCV_opencv_bgsegm_FOUND=TRUE
-- OpenCV_opencv_bioinspired_FOUND=TRUE
-- OpenCV_opencv_calib3d_FOUND=TRUE
-- OpenCV_opencv_ccalib_FOUND=TRUE
-- OpenCV_opencv_core_FOUND=TRUE
[...]
```

For example, OpenCV_DIR could then be used to provide a better default for the cassifier path (currently hardcoded) here: 
https://github.com/dyne/frei0r/blob/e6057edba7820c51f15e10875d3e580fc40adbb1/src/filter/facedetect/facedetect.cpp#L66.
