### ISSUE TITLE
Installation location of pkgconfig files is hardcoded

### ISSUE THREAD

**Issue by Othko97** [dyne/frei0r#79]
Currently the installation location of pkgconfig files is hardcoded to `${CMAKE_INSTALL_PREFIX}/lib/pkgconfig`, which causes issues if the system pkg-config is configured to use a different location. 

For example in [freedesktop-sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk) we use debian's multiarch system, with our pkg-config path configured to be in `/usr/lib/${multiarch-triplet}/pkgconfig`. As a result we wouldn't be able to use pkg-config to detect frei0r. See the work to add frei0r support in freedesktop-sdk [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/1234) for an example of the issue.

**Comment by ddennedy** [comment]
Will using CMAKE_INSTALL_LIBDIR work for you?

**Comment by Othko97** [comment]
We already set CMAKE_INSTALL_LIBDIR, the problem is that the installation is hardcoded as `lib/pkgconfig`. If preferred I can change #80 to just use `${CMAKE_INSTALL_DIR}/pkgconfig`, as this seems sensible and less maintenance than an option.

**Comment by ddennedy** [comment]
frei0r using libdir is what I meant. I would prefer the smaller patch you suggested. Thanks
