### ISSUE TITLE
facebl0r not working

### ISSUE THREAD

**Issue by etherz10** [dyne/frei0r#91]
After getting OpenCV installed from source and following your installation instructions of

1. Clone repo
2. `./autogen.sh`
3. `./configure`

```
Compile frei0r-plugins 1.6.1 for x86_64-unknown-linux-gnu

    - INSTALL prefix: /usr/local
    - CPU optimization: YES
    - opencv: YES
              data dir:
    - gavl: NO
            gavl >= 0.2.3 not found - this program enables optional
            plugin with the gmerlin audio video library >= 0.2.3
            http://gmerlin.sourceforge.net/
    - cairo: NO
            cairo >= 1.0.0 not found - this program enables optional
            plugin with the Cairo 2D vector graphics library >= 1.0.0
            http://www.cairographics.org/

Now you can run make.
```

4. `make -j`
5. `sudo make install`

Doing this seems to put a `facebl0r.so` in both `/usr/local/lib/frei0r-1/facebl0r.so` & `/home/USER/frei0r/src/.libs/facebl0r.so`

Moving either of these to a directory where FFmpeg can pick it up and run running `ffmpeg -v debug -i ~/samplevideo.mp4 -vf "frei0r=facebl0r" ~/facebl0rtest.mp4` seems to run through the process but the final file is the same as the original with no effects applied?

**Comment by StefanBruens** [comment]
Does the debug output mention which color format is passed to the facebl0r plugin?
