### ISSUE TITLE
Please add new release

### ISSUE THREAD

**Issue by kikislater** [dyne/frei0r#92]
Hi,

Regarding this discussion :
https://forum.shotcut.org/t/new-filter-not-present-in-ui/14224
and as Shotcut announce new plugins, it needs a new release of frei0r-plugins.

Please add a new release or tag to make upstream packages and dependent packages up to date in all distributions and not depending on git master version.

**Comment by jaromil** [comment]
done! 1.7.0 is out, see https://lists.dyne.org/lurker/message/20191206.162823.cee9dd6f.en.html

**Comment by kikislater** [comment]
Thank you !
